version: '3.0'

services:
  paratonnerre:
    container_name: paratonnerre
    image: caner-emec/paratonnerre:latest
    restart: always
    network_mode: host
    volumes:
      - ./:/app
    environment:
      - CHANNEL_NAME=mychannel
      - CHAINCODE_NAME=basic
      - PEER_NAME=peer0.org1.example.com
      - MSP_ID=Org1MSP
      - PEER_ENDPOINT=localhost:7051
      - PEER_HOST_ALIAS=peer0.org1.example.com
      - CRED_USER_CERT_PATH=./src/credentials/cert.pem
      - CRED_USER_PRIVKEY_PATH=./src/credentials/priv_sk
      - CRED_PEER_TLS_CERT_PATH=./src/credentials/ca.crt
      # Kafka settings
      - KAFKA_BROKER1_ADDRESS=localhost:29092
      - KAFKA_BROKER2_ADDRESS=localhost:39092
      - KAFKA_TOPIC_HLF_BLOCKS=hlf_blocks
      - KAFKA_TOPIC_HLF_TRANSACTION=hlf_transaction
